POST http://192.168.56.1:8080/api/transaction HTTP/1.1
content-type: application/json

{
    "title": "test transaction",
    "amount": 100,
    "owner": {"id": 1},
    "group_ent": {"id": 1},
    "involved": [{"user": {"id": 1}, "amount": 100 } ]
}
########################


GET http://192.168.56.1:8080/api/transaction?groupId=1