POST http://192.168.56.1:8080/api/transaction HTTP/1.1
content-type: application/json

{
    "title":"asd",
    "description":"asd",
    "amount":9,
    "owner":{"id":1},
    "group":{"id":1},
    "involved":[{"user":{"id":7},"amount":1.5},
                {"user":{"id":12},"amount":1.5},
                {"user":{"id":11},"amount":1},
                {"user":{"id":15},"amount":1},
                {"user":{"id":8},"amount":1},
                {"user":{"id":3},"amount":1},
                {"user":{"id":14},"amount":1},
                {"user":{"id":5},"amount":1}]
}

########################

GET http://192.168.56.1:8080/api/transaction?groupId=1

###########################

POST http://192.168.56.1:8080/api/group HTTP/1.1
content-type: application/json

{
    "name":"test Group",
    "icon":"",
    "members":[{"id":7},{"id":1}]
}